/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Brand colors
        'deep-navy': '#0D1B2A',
        'ice-cyan': '#00BCD4',
        'warm-copper': '#C77B3F',
        'copper-light': '#E0A96D',
        'frost-white': '#F4F8FB',
        'pale-blue': '#E0F2F7',
        'steam-blue': '#90CAF9',
        'neutral-dark': '#1C1C1C',
        'neutral-mid': '#6B6B6B',

        // Material Design surface tokens
        'surface': '#0f1416',
        'surface-dim': '#0f1416',
        'surface-bright': '#353a3c',
        'surface-container-lowest': '#0a0f11',
        'surface-container-low': '#171c1f',
        'surface-container': '#1b2023',
        'surface-container-high': '#262b2d',
        'surface-container-highest': '#313538',
        'on-surface': '#dfe3e6',
        'on-surface-variant': '#bbc9cc',
        'inverse-surface': '#dfe3e6',
        'inverse-on-surface': '#2c3134',
        'outline': '#869396',
        'outline-variant': '#3c494c',
        'surface-tint': '#44d8f1',
        'primary': '#44d8f1',
        'on-primary': '#00363e',
        'primary-container': '#00bcd4',
        'on-primary-container': '#004650',
        'inverse-primary': '#006876',
        'secondary': '#ffb783',
        'on-secondary': '#4f2500',
        'secondary-container': '#743900',
        'on-secondary-container': '#faa565',
        'tertiary': '#bac8dc',
        'on-tertiary': '#243141',
        'tertiary-container': '#9eacc0',
        'on-tertiary-container': '#334051',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        'logo': ['Bebas Neue', 'sans-serif'],
        'display-lg': ['Montserrat'],
        'headline-lg': ['Montserrat'],
        'headline-lg-mobile': ['Montserrat'],
        'headline-md': ['Montserrat'],
        'headline-sm': ['Montserrat'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-caps': ['Montserrat'],
        'quote-italic': ['Montserrat'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
        'quote-italic': ['20px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        'section-gap': '120px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1280px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'gutter': '24px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
};